### ISSUE TITLE
[Improvement] Documentation: Changelog generation

### ISSUE THREAD

**Issue by fuhlig** [csshugs/FluidMS#7]
Good choice by using conventional commits.
This layed the groundwork for automation:
- changelog generation
  - [conventional changelog](https://github.com/conventional-changelog/conventional-changelog)
  - [standard-version](https://github.com/conventional-changelog/standard-version)
  - [article](https://medium.com/jobtome-engineering/how-to-generate-changelog-using-conventional-commits-10be40f5826c)
There are many options, needs evaluation

- ~~commit linting~~
~~Tools like [commitlint](https://github.com/conventional-changelog/commitlint) can lint commit messages according to contributing guidelines~~
[commit linting is now a separate feature (#9)]

Let me know what you think and we can break those tasks (evaluation, implementation etc.) down

**Comment by csshugs** [comment]
Ok, I already checked out standard-version. I have a [poc-branch open](https://github.com/csshugs/FluidMS/compare/develop...poc/7/changelog-automation), so you can check it out. The CHANGELOG.md generation happens via a `$ npm run release`. This works well, but really forces us to squash our commits when merging PRs. Otherwise **every** commit is regarded as an individual entry in the generated changelog. I’m fine with squashing commits. The question is how to lint them when squashing via the GitHub UI.

**Comment by csshugs** [comment]
Or should we rather just squash manually (locally) when merging `develop` into `master`?

**Comment by csshugs** [comment]
Apart from all that, I think that linting commits is a really good idea and we can tackle that as a separate feature, as I consider that independent from changelog generation. 

@fuhlig I've taken the liberty of updating your [initial comment](https://github.com/csshugs/FluidMS/issues/7#issue-493623219) and changing the issue title accordingly.

See #9

**Comment by csshugs** [comment]
#17 is merged.
